---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
      #    -   id: trailing-whitespace
      #    -   id: end-of-file-fixer
      #    -   id: check-yaml
  - id: check-added-large-files
  - id: check-case-conflict
      # - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
      # - id: check-json


    # -   id: flake8
    #     args: [--max-line-length=100]
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3.8
    args: [-l, '110']
#- repo: https://github.com/adrienverge/yamllint.git
#  rev: v1.26.1    # or higher tag
#  hooks:
#  - id: yamllint
#    args: [--format, parsable]
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.0    # or specific tag
  hooks:
  - id: yamlfmt
#    args: [--mapping, '2', --sequence, '2', --offset, '0', --colons, --width, '150']
    args: [--width, '150']


#exclude: .bumpversion.cfg

files: (^src/.*py)|(.*yaml)

# sigil ed72523bfd2eaafabb2cfb97013d6b86
