---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
# - id: trailing-whitespace
# - id: end-of-file-fixer
# - id: check-yaml
# - id: check-json
# - id: check-docstring-first
# -   id: flake8
#     args: [--max-line-length=100]
- repo: https://github.com/psf/black
  rev: 21.10b0
  hooks:
  - id: black
    language_version: python3.8
    args: [-l, '110']
#- repo: https://github.com/adrienverge/yamllint.git
#  rev: v1.26.1    # or higher tag
#  hooks:
#  - id: yamllint
#    args: [--format, parsable]
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.0 # or specific tag
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150', --preserve-quotes]

#            args: [--mapping, '2', --sequence, '0', --offset, '0', --width, '150']


#exclude: .bumpversion.cfg

files: (^src/.*py)|(.*yaml)

# sigil fdeec8e63ab62c258e90cb36d22eb928
