[project]
name = "PyContracts3"
version = "7.2"
authors = [{name = "Andrea Censi", email = "andrea@zupermind.com"}]
dependencies = ["pyparsing<3", "decorator<5", "six", "future", "numpy"]

[project.scripts]

[tool]
[tool.poetry]
name = "PyContracts3"
version = "7.2"
description = ""
authors = ["Andrea Censi <andrea@zupermind.com>"]
packages = [{include = "contracts", from = "src"}, {include = "contracts/library", from = "src"}, {include = "contracts/useful_contracts", from = "src"}]

[tool.setuptools]
packages = ["contracts", "contracts.library", "contracts.useful_contracts"]
package-dir = {"" = "src"}
